services:
  tests:
    container_name: pytest-runner
    working_dir: /app
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./allure-results:/app/allure-results

    command: >
      ./run.sh
