version: "3.9"

services:
  tests:
    build: .
    container_name: pytest-runner
    volumes:
      - .:/app
      - allure-results:/app/allure-results
    working_dir: /app
    command: >
      pytest
      --alluredir=/app/allure-results
    depends_on:
      - allure

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-service
    ports:
      - "5050:5050"
    volumes:
      - allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 5
      KEEP_HISTORY: 1

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"

volumes:
  allure-results:
